/* Generated By:JJTree: Do not edit this line. AskUserExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class AskUserExp extends SimpleNode {
  public AskUserExp(int id) {
    super(id);
  }

  public AskUserExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a3b0d1533ada14d61e9cbbaad435f2b (do not edit this line) */
