/* Generated By:JJTree: Do not edit this line. Binding.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Binding extends SimpleNode {
  public Binding(int id) {
    super(id);
  }

  public Binding(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de90e36d70068f3110d64e01a14243a5 (do not edit this line) */
