/* Generated By:JJTree&JavaCC: Do not edit this line. CalcParserConstants.java */
package AST;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int NI = 7;
  /** RegularExpression Id. */
  int ASK = 8;
  /** RegularExpression Id. */
  int USER = 9;
  /** RegularExpression Id. */
  int FPLIT = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int MUL = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int QUESTION = 14;
  /** RegularExpression Id. */
  int ID = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"let\"",
    "\"in\"",
    "\"ni\"",
    "\"ask\"",
    "\"user\"",
    "<FPLIT>",
    "\"=\"",
    "\"*\"",
    "\",\"",
    "\"?\"",
    "<ID>",
    "\"/\"",
  };

}
