/* Generated By:JJTree: Do not edit this line. DivExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class DivExp extends SimpleNode {
  public DivExp(int id) {
    super(id);
  }

  public DivExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fccea4b6bee3d0cbf361b2bd96999511 (do not edit this line) */
