/* Generated By:JJTree: Do not edit this line. FPLitExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class FPLitExp extends SimpleNode {    

  float numero;
  
  public FPLitExp(int id) {
    super(id);
  }

  public FPLitExp(CalcParser p, int id) {
    super(p, id);
  }
  
  public void setFPLIT(String image){
      numero = Float.parseFloat(image);
  }
  

}
/* JavaCC - OriginalChecksum=745e48bad46ec6479856a4099ba035f6 (do not edit this line) */
