/* Generated By:JJTree: Do not edit this line. IdExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class IdExp extends SimpleNode {
  String identificador;
  public IdExp(int id) {
    super(id);
  }

  public IdExp(CalcParser p, int id) {
    super(p, id);
  }

  public void setID(String image){
      identificador = image;
  }
  
}
/* JavaCC - OriginalChecksum=403c931954582758637b6e6c5db337e9 (do not edit this line) */
