/* Generated By:JJTree: Do not edit this line. IdExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class IdExp extends SimpleNode {
  
  String identificador;  
    
  public IdExp(int id) {
    super(id);
  }

  public IdExp(CalcParser p, int id) {
    super(p, id);
  }
  
  public void setID(String image){
      identificador = image;
  }

}
/* JavaCC - OriginalChecksum=855e20b60802bf2b6f95b3b1ee18a32d (do not edit this line) */
