/* Generated By:JJTree: Do not edit this line. List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class List extends SimpleNode {
  public List(int id) {
    super(id);
  }

  public List(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c55f8e20c0954820c248c3cbff27864 (do not edit this line) */
