/* Generated By:JJTree: Do not edit this line. MulExp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class MulExp extends SimpleNode {
  public MulExp(int id) {
    super(id);
  }

  public MulExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0144fe830020e17c677a1ebb19804373 (do not edit this line) */
