/* Generated By:JJTree: Do not edit this line. Opt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Opt extends SimpleNode {
  public Opt(int id) {
    super(id);
  }

  public Opt(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa31756ad5cf4581f3a5dfa3c43b38d9 (do not edit this line) */
