/* Generated By:JJTree: Do not edit this line. Opt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Opt extends SimpleNode {
  public Opt(int id) {
    super(id);
  }

  public Opt(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b0458515a69ac8e11bd6812f2c87260 (do not edit this line) */
