/* Generated By:JJTree: Do not edit this line. Start.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Start extends SimpleNode {
  public Start(int id) {
    super(id);
  }

  public Start(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6485f2b2dc6782a548bb77bf6ed1370 (do not edit this line) */
