/* Generated By:JJTree: Do not edit this line. AskUserExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class AskUserExp extends SimpleNode {
  public AskUserExp(int id) {
    super(id);
  }

  public AskUserExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5ffe63f7c674d35d2922c752522fd00 (do not edit this line) */
