/* Generated By:JJTree: Do not edit this line. Binding.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Binding extends SimpleNode {
  public Binding(int id) {
    super(id);
  }

  public Binding(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52f7bf2803f81122479cf90dbf6c07ec (do not edit this line) */
