/* Generated By:JavaCC: Do not edit this line. CalcParserTreeConstants.java Version 5.0 */
package AST;

public interface CalcParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTMULEXP = 2;
  public int JJTDIVEXP = 3;
  public int JJTLETEXP = 4;
  public int JJTLIST = 5;
  public int JJTBINDING = 6;
  public int JJTFPLITEXP = 7;
  public int JJTIDEXP = 8;
  public int JJTASKUSEREXP = 9;
  public int JJTOPT = 10;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "MulExp",
    "DivExp",
    "LetExp",
    "List",
    "Binding",
    "FPLitExp",
    "IdExp",
    "AskUserExp",
    "Opt",
  };
}
/* JavaCC - OriginalChecksum=51ff8323f73f32d6e76fadbc04a33946 (do not edit this line) */
