/* Generated By:JJTree: Do not edit this line. MulExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class MulExp extends SimpleNode {
  public MulExp(int id) {
    super(id);
  }

  public MulExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=219c6f7e1112d1bd7f62663f850cb26f (do not edit this line) */
