/* Generated By:JJTree: Do not edit this line. Start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Start extends SimpleNode {
  public Start(int id) {
    super(id);
  }

  public Start(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3ed1237769518b136f2ec4e5455bace (do not edit this line) */
